export const learningStages = [
  {
    id: 'foundations',
    level: 'BEGINNER',
    title: 'Start with the foundations',
    summary: 'Learn what the assets represent before looking at their prices.',
    topics: ['How public ledgers record transactions', 'Coins, tokens, stablecoins, and network fees', 'The differences between Bitcoin, Ethereum, and exchanges'],
    practice: 'Explain in your own words how a cryptocurrency, its network, and a wallet differ. Read the Bitcoin and Ethereum entries on the homepage.',
    checkpoint: 'Can you describe what a blockchain records and what a wallet actually stores?',
  },
  {
    id: 'custody',
    level: 'BEGINNER',
    title: 'Understand wallets and custody',
    summary: 'Learn how keys authorize transactions and why custody changes your risks.',
    topics: ['Private keys, public addresses, and recovery phrases', 'Custodial exchange accounts versus self-custody', 'Hardware wallets, phishing, and transaction approval'],
    practice: 'Explore a wallet interface without funding it. Identify the recovery phrase warning, network selector, and transaction confirmation details.',
    checkpoint: 'Could you explain why a recovery phrase must never be shared or entered into an unsolicited website?',
  },
  {
    id: 'networks',
    level: 'BEGINNER',
    title: 'Follow a transaction through a network',
    summary: 'See how a signed transaction becomes part of a chain and what explorers reveal.',
    topics: ['Blocks, confirmations, and transaction finality', 'Proof of work and proof of stake at a high level', 'Network fees, congestion, and block explorers'],
    practice: 'Use a public block explorer to inspect an old, well-known transaction. Find its fee, block, confirmations, and sender/recipient addresses.',
    checkpoint: 'Can you distinguish a transaction being broadcast from one being included and finalized?',
  },
  {
    id: 'market-mechanics',
    level: 'BEGINNER TO INTERMEDIATE',
    title: 'Learn how markets work',
    summary: 'Understand the mechanics behind a quote, chart, and completed trade.',
    topics: ['Spot markets versus futures and perpetual contracts', 'Market and limit orders, bids, asks, and order books', 'Spread, liquidity, slippage, volume, and volatility', 'Candlesticks, timeframes, market cap, and circulating supply'],
    practice: 'Watch a liquid market without placing an order. Note the bid/ask spread and compare the quoted price with a hypothetical market-order fill.',
    checkpoint: 'Can you explain why low liquidity can make the execution price differ from the displayed price?',
  },
  {
    id: 'research',
    level: 'INTERMEDIATE',
    title: 'Build an independent research process',
    summary: 'Compare evidence from project documentation, market data, and on-chain activity.',
    topics: ['Protocol documentation, governance, and token utility', 'Supply schedules, vesting, unlocks, and dilution', 'Fundamental, on-chain, and technical analysis', 'Source quality, incentives, and conflicting claims'],
    practice: 'Choose one asset to study on paper. Read its official documentation, inspect supply data, and write down what evidence would change your view.',
    checkpoint: 'Can you tell the difference between an observable metric, an interpretation, and a promotional claim?',
  },
  {
    id: 'risk',
    level: 'INTERMEDIATE',
    title: 'Practice risk management before trading',
    summary: 'Turn uncertainty into explicit limits and test a process without risking money.',
    topics: ['Position sizing and defining maximum acceptable loss', 'Trade thesis, invalidation, and an activity journal', 'Paper trading, fees, and realistic execution assumptions', 'Why leverage can magnify losses and liquidation risk'],
    practice: 'Keep a paper-trading journal for several weeks. Record the reason for each hypothetical entry, invalidation point, fees, and what you learned afterward.',
    checkpoint: 'Can you state your maximum loss and exit conditions before considering an entry?',
  },
  {
    id: 'advanced-markets',
    level: 'ADVANCED',
    title: 'Study advanced market structure',
    summary: 'Use derivatives and order-flow data carefully; none of these signals predicts outcomes on its own.',
    topics: ['Funding rates, open interest, basis, and liquidations', 'Order-book depth and execution across venues', 'Options concepts such as volatility and expiry', 'Backtesting pitfalls, look-ahead bias, and survivorship bias'],
    practice: 'Compare funding rate and open interest across more than one source. Write down alternative explanations instead of treating a metric as a directional signal.',
    checkpoint: 'Can you identify what a dataset omits and how that could distort a conclusion?',
  },
  {
    id: 'advanced-onchain',
    level: 'ADVANCED',
    title: 'Analyze protocols and on-chain applications',
    summary: 'Look beyond token prices to contracts, incentives, and dependencies.',
    topics: ['DeFi liquidity, collateral, oracles, and liquidation mechanisms', 'Smart-contract permissions, audits, and upgrade controls', 'Total value locked and the limits of comparative metrics', 'Governance concentration, bridge risk, and composability'],
    practice: 'Trace one application interaction from its user interface to the contract and underlying dependencies using public documentation and read-only explorers.',
    checkpoint: 'Can you name the protocol dependencies that could fail even if its main contract works as designed?',
  },
]
